# Snakemake config
input:
output: 'giantpandrna.out/'
log: 'giantpandrna/giantpandrna.log'
threads: 16
kit: 'DCS109'



# for installDB.smk
species: 'Rat'
referenceDir: 'RatDB'

# Snakemake Params
MassiveJobMem: 350000   
BigJobMem: 32000     
BigJobCpu: 16       
MediumJobCpu: 4     
SmallJobMem: 4000
SmallJobCpu: 1 

SmallTime: 5
BigTime: 300
MediumTime: 120
MassiveTime: 1320
